# Generated by Django 4.2 on 2023-05-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
