# Generated by Django 4.2.1 on 2023-05-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_course_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='msg',
            field=models.TextField(null=True),
        ),
    ]
