# Generated by Django 4.2.1 on 2023-05-15 16:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_result_perc'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dran',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
