# Generated by Django 4.2.1 on 2023-05-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_question_dran'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='typ',
            field=models.IntegerField(default=0),
        ),
    ]
