# Generated by Django 4.2.1 on 2023-05-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exp',
            field=models.TextField(default='no explanetion'),
        ),
    ]
