# Generated by Django 4.2.1 on 2023-06-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_question_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
