# Generated by Django 4.2.2 on 2023-06-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_question_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='c_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='departiment',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
