# Generated by Django 4.2.2 on 2023-06-26 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_question_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='year_now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, null=True)),
                ('sem', models.IntegerField(null=True)),
                ('tot', models.IntegerField(null=True)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.departiment')),
            ],
        ),
    ]
