# Generated by Django 4.2.2 on 2023-06-28 15:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_tables_question_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='datr',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='qid',
        ),
        migrations.CreateModel(
            name='Table_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.tables')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.table_data'),
        ),
    ]
