# Generated by Django 4.2.2 on 2023-06-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_remove_table_data_table_tables_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='table',
        ),
    ]
