# Generated by Django 4.2.2 on 2023-06-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_remove_question_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tabl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.tables'),
        ),
    ]
