# Generated by Django 4.2.2 on 2023-06-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_question_tabl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='dt',
        ),
        migrations.AddField(
            model_name='tables',
            name='dt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.table_data'),
        ),
    ]
