# Generated by Django 4.2.2 on 2023-06-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_remove_tables_dt_tables_data1_tables_data10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='para',
            field=models.TextField(null=True),
        ),
    ]
