# Generated by Django 4.2.2 on 2023-07-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_question_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='short',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
