# Generated by Django 4.2.2 on 2023-07-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_assiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assiment',
            name='m',
            field=models.IntegerField(null=True),
        ),
    ]
