# Generated by Django 4.2 on 2023-04-09 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.IntegerField(null=True)),
                ('time', models.TimeField(null=True)),
                ('tim', models.CharField(max_length=100, null=True)),
                ('dat', models.DateField(null=True)),
                ('dur', models.IntegerField(null=True)),
                ('adby', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/Teacher/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('depart', models.CharField(choices=[('1', 'Computer Science'), ('3', 'Natural Resource Management'), ('4', 'Agri-business and value chain management'), ('5', 'Animal Scince'), ('6', 'Plant Science'), ('7', 'Horticulture'), ('8', 'Veterinary Science'), (' 9', ' Chemistry'), ('10', 'Biology'), ('11', 'Mathematics'), ('12', 'Statics'), ('13', 'Agricultural Economics'), ('14', 'Physics'), ('15', 'Accounting and finance'), ('16', 'management'), ('17', 'Economics'), ('18', 'Veterinary Medicine'), ('19', 'Turism and Hotel Management'), ('20', 'psychology'), ('19', 'Turism and Hotel Management'), ('20', 'psychology'), ('21', 'Geograpy'), ('22', 'Civic'), ('23', 'Social Anthrophology'), ('24', 'History And Heritage management'), ('25', ' English Languege'), ('26', 'Law'), ('27', 'Midwifery'), ('20', 'Nursing'), ('20', 'Public Health')], max_length=255, null=True)),
                ('course', models.CharField(max_length=255, null=True)),
                ('type', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
