# Generated by Django 4.2.2 on 2023-06-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dep',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sem',
            field=models.IntegerField(null=True),
        ),
    ]
