# Generated by Django 4.2 on 2023-04-09 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('mot_count', models.IntegerField(null=True)),
                ('material', models.CharField(max_length=255, null=True)),
                ('user', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/Student/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('dep', models.IntegerField(null=True)),
                ('regby', models.IntegerField(null=True)),
                ('ex_status', models.IntegerField(default=0)),
                ('sid', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('fname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('motion', models.IntegerField(default=0)),
                ('obj', models.CharField(max_length=255, null=True)),
                ('insession', models.BooleanField(default=True)),
                ('sem', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.IntegerField(null=True)),
                ('message', models.TextField(null=True)),
                ('replay', models.TextField(null=True)),
                ('pending', models.CharField(max_length=255, null=True)),
                ('depsend', models.TextField(null=True)),
                ('receiver', models.IntegerField(null=True)),
                ('messega', models.ManyToManyField(to='teacher.teacher')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('motion', models.CharField(max_length=255, null=True)),
                ('mot_count', models.IntegerField(default=0)),
                ('material', models.CharField(max_length=255, null=True)),
                ('exam', models.IntegerField(null=True)),
                ('dat', models.DateTimeField(auto_now=True)),
                ('tyme', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
