# Generated by Django 4.2.1 on 2023-05-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_sms_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_feedback',
            name='fname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sms_feedback',
            name='lname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
