# Generated by Django 4.2.1 on 2023-05-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_sms_feedback_fname_sms_feedback_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_feedback',
            name='seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('costom', 'costome'), ('male', 'male'), ('female', 'female')], max_length=255, null=True),
        ),
    ]
