# Generated by Django 4.2.1 on 2023-05-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_sms_feedback_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('costom', 'costome')], max_length=255, null=True),
        ),
    ]
