# Generated by Django 4.2.1 on 2023-05-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('costom', 'costome'), ('female', 'female')], max_length=255, null=True),
        ),
    ]
