# Generated by Django 4.2.1 on 2023-06-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_code',
            field=models.IntegerField(default=1),
        ),
    ]
