# Generated by Django 4.2.2 on 2023-06-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_student_exam_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('costom', 'costome')], max_length=255, null=True),
        ),
    ]
