# Generated by Django 4.2.2 on 2023-06-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_answer_lanswer_answer_lreal_alter_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('costom', 'costome')], max_length=255, null=True),
        ),
    ]
