# Generated by Django 4.2.2 on 2023-07-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gen',
            field=models.CharField(choices=[('female', 'female'), ('costom', 'costome'), ('male', 'male')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('costom', 'costome'), ('male', 'male')], max_length=255, null=True),
        ),
    ]
