# Generated by Django 4.2.2 on 2023-07-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0043_student_gen_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tes',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gen',
            field=models.CharField(choices=[('costom', 'costome'), ('male', 'male'), ('female', 'female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('costom', 'costome'), ('male', 'male'), ('female', 'female')], max_length=255, null=True),
        ),
    ]
