# Generated by Django 4.2.2 on 2023-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_answer_tes_alter_student_gen_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gen',
            field=models.CharField(choices=[('costom', 'costome'), ('female', 'female'), ('male', 'male')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('costom', 'costome'), ('female', 'female'), ('male', 'male')], max_length=255, null=True),
        ),
    ]
