# Generated by Django 4.2.2 on 2023-07-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_alter_student_gen_alter_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip_adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=222, null=True, unique=True)),
                ('tim', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='gen',
            field=models.CharField(choices=[('costom', 'costome'), ('female', 'female'), ('male', 'male')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('costom', 'costome'), ('female', 'female'), ('male', 'male')], max_length=255, null=True),
        ),
    ]
