# Generated by Django 4.2.2 on 2023-07-03 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0047_ip_adress_alter_student_gen_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_adress',
            name='host',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ip_adress',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='gen',
            field=models.CharField(choices=[('costom', 'costome'), ('male', 'male'), ('female', 'female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('costom', 'costome'), ('male', 'male'), ('female', 'female')], max_length=255, null=True),
        ),
    ]
