# Generated by Django 4.2.10 on 2024-03-25 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0050_alter_student_gen_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gen',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('costom', 'costome')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('costom', 'costome')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Loged_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=255, null=True)),
                ('ip', models.CharField(max_length=255, null=True)),
                ('tim', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
