# Generated by Django 4.2.10 on 2024-03-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0051_alter_student_gen_alter_student_gender_loged_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loged_user',
            name='exam',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gen',
            field=models.CharField(choices=[('female', 'female'), ('costom', 'costome'), ('male', 'male')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('costom', 'costome'), ('male', 'male')], max_length=255, null=True),
        ),
    ]
