# Generated by Django 4.2.10 on 2024-03-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0052_loged_user_exam_alter_student_gen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_adress',
            name='exam',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gen',
            field=models.CharField(choices=[('male', 'male'), ('costom', 'costome'), ('female', 'female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('costom', 'costome'), ('female', 'female')], max_length=255, null=True),
        ),
    ]
