# Generated by Django 4.2.10 on 2024-03-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0053_ip_adress_exam_alter_student_gen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loged_user',
            name='exam',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
